server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydb.cfmdzu2osbdy.ap-northeast-2.rds.amazonaws.com:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: adminadmin

  jpa:
    hibernate:
      naming:
        # Entity Table 대소문자 구분
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # Initial Data config
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: togedutch
    password: kpkmtswkmhykiceg

  # file upload max size
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB

  jackson:
    timeZone: Asia/Seoul
    dateFormat: yyyy-MM-dd HH:mm:ss

  # Swagger 오류 발생 시 추가
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      accessKey: AKIAUHMSHLSB36RJNUFK
      secretKey: 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
    # AWS S3 bucket Info
    s3:
      bucket: umcbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    url: https://umcbucket.s3.ap-northeast-2.amazonaws.com/

naver-cloud-sms:
  accessKey: gDq946gaJC6EVWaoQTa8
  secretKey: OfKAcENU5iYw77s2biiYdMWkX7TYg1CLWm8XgHmL
  serviceId: ncp:sms:kr:300023321554:togedutch_sms
  senderPhone: 01046408115